### ISSUE TITLE
SPARQL DESCRIBE

### ISSUE THREAD

**Issue by renespeck** [AKSW/KATANA#1]
Is "DESCRIBE " in [1] really the  CBD? 

> The description is determined by the query service [https://www.w3.org/TR/rdf-sparql-query/#describe]

[1]https://github.com/AKSW/KATANA/blob/master/src/main/java/org/aksw/simba/katana/KBUtils/SparqlHandler.java#L41

**Comment by RicardoUsbeck** [comment]
A CBD is not clearly defined. CBD can be implemented by DESCRIBE but DESCRIBE varies from triple store to triple store. For a first version this is enough, for a later version we should look into https://www.w3.org/Submission/CBD/

**Comment by renespeck** [comment]
That is what I found too.  To implement an extension of a CBD, I think we  first need a correct implementation of the CBD. 

thanks for confirming.

**Comment by mommi84** [comment]
Hello, I suppose you assigned me this issue by mistake. :)
